spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.19.133:2181
  protocol:
    port: 28810
